services:
  - type: web
    name: word-to-pdf-converter
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libreoffice-core libreoffice-writer
      pip install -r requirements.txt
    startCommand: gunicorn Word2PDF:app
    plan: free